/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#aec7f6',
        'on-surface': '#111c2d',
        outline: '#74777f',
        'secondary-fixed-dim': '#acc7ff',
        'on-error-container': '#93000a',
        'on-surface-variant': '#44474e',
        'surface-container': '#e7eeff',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'inverse-on-surface': '#ecf1ff',
        'secondary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#aec7f6',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#261a00',
        'on-secondary-fixed': '#001a40',
        'primary-fixed': '#d6e3ff',
        'surface-dim': '#cfdaf2',
        'secondary-container': '#659dfe',
        'surface-container-highest': '#d8e3fb',
        background: '#f9f9ff',
        error: '#ba1a1a',
        'primary-container': '#002147',
        'on-error': '#ffffff',
        'on-secondary-container': '#003370',
        secondary: '#115cb9',
        'on-primary': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'outline-variant': '#c4c6cf',
        primary: '#000a1e',
        'on-primary-fixed-variant': '#2d476f',
        surface: '#f9f9ff',
        'on-tertiary-container': '#ae8100',
        'on-tertiary-fixed-variant': '#5c4300',
        'tertiary-fixed-dim': '#fbbc00',
        'on-primary-fixed': '#001b3d',
        'on-background': '#111c2d',
        'surface-container-high': '#dee8ff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#004491',
        'tertiary-container': '#2d1f00',
        'on-primary-container': '#708ab5',
        'tertiary-fixed': '#ffdfa0',
        tertiary: '#100900',
        'inverse-surface': '#263143',
        'surface-tint': '#465f88',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        xl: '80px',
        'container-max': '1280px',
        base: '8px',
        gutter: '24px',
        md: '24px',
        sm: '12px',
        lg: '48px',
      },
      fontFamily: {
        'title-lg': ['Inter'],
        'body-md': ['Inter'],
        caption: ['Inter'],
        'display-lg': ['"Playfair Display"'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['"Playfair Display"'],
        'headline-md': ['"Playfair Display"'],
      },
      fontSize: {
        'title-lg': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
